### ISSUE TITLE
Tests for parental list 

### ISSUE THREAD

**Issue by omarbenites** [omarbenites/fbmlist#1]
:telescope: 

- Error1: The lack of female parents or male parents 
 message: "Please fill male (female) parents"

-Error 2: The lack of female and male parents 

- Error 3 : Parental list with the same
message: "This list already exist. Please write another name"

-Error3: Empty new parental list name
message: Fill the parent list name

-Error 4: 
message:

**Comment by cipriuhq** [comment]
now fixed.
